  grafana:
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: unless-stopped
    depends_on:
      - "influxdb"
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
