  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ./services/mariadb/mariadb.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ./volumes/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped

