  openhab:
    image: "openhab/openhab:latest"
    container_name: openhab
    restart: unless-stopped
    depends_on:
      - "mariadb"
      - "influxdb"
      - "mosquitto"
    network_mode: host
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
    depends_on:
      - mariadb
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volumes/openhab/addons:/openhab/addons"
      - "./volumes/openhab/conf:/openhab/conf"
      - "./volumes/openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Copenhagen -Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0"
#    # The command node is very important. It overrides
#    # the "gosu openhab tini -s ./start.sh" command from Dockerfile and runs as root!
#    command: "tini -s ./start.sh server"
